spring.application.name=Inventory
spring.datasource.url=jdbc:postgresql://localhost:5432/Microservices
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
