spring.application.name=SpringBootJPQL
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringBootDB
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8081