spring.application.name=securityApp
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/SpringSecurityDB
spring.datasource.username=postgres
spring.datasource.password=TIGER

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
